/* 
	MySQL Script generated by MySQL Workbench
	Wed May  7 10:22:50 2025
	Model: New Model    Version: 1.0
	MySQL Workbench Forward Engineering
/*
/*
	Criado por: Pedro Queiroga
	Data criação: 07/05/2025 10h22
	Motivo: Permitir que a aplicação grave informações do usuário, publicação e curtidas
*/
/*
	Alterado por: Marquescharlon
	Data alteração: 12/06/2025 15h30
	Motivo: Agrupar comandos SQL que são necessários e que estão em outros arquivos no repositório.
*/

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` longtext NOT NULL,
  `Imagem` VARCHAR(255) NULL,
  `UsuarioId` INT NULL,
  `dataPublicao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpost`),
  INDEX `UsuarioId_idx` (`UsuarioId` ASC) VISIBLE,
  CONSTRAINT `UsuarioId`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `id_usuario` INT NULL,
  `data` DATETIME NULL,
  `post_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcomentario`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Publicacao` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `idlikes` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`idlikes`),
  UNIQUE INDEX `unique_user_post` (`id_usuario` ASC, `id_post` ASC) VISIBLE,
  INDEX `id_post_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_likes_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_id_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`Publicacao` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

ALTER TABLE PUBLICACAO ADD COLUMN EXCLUIDO TINYINT(1) DEFAULT 0 NOT NULL;

ALTER TABLE PUBLICACAO 
	ADD COLUMN DATAEXCLUSAO DATETIME,
	ADD COLUMN EXCLUIDOPOR INT,
	ADD CONSTRAINT FK_EXCLUIDO_POR FOREIGN KEY (EXCLUIDOPOR) REFERENCES USUARIO(IDUSUARIO);

-- ADICIONAR COLUNA DE FOTO DE PERFIL NA TABELA USUARIO
ALTER TABLE `mydb`.`Usuario` 
	ADD COLUMN `foto_perfil` VARCHAR(255) NULL AFTER `created_at`;

-- CRIAR TABELA DE DISLIKES
CREATE TABLE IF NOT EXISTS `mydb`.`dislikes` (
  `iddislikes` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`iddislikes`),
  UNIQUE INDEX `unique_user_post_dislike` (`id_usuario` ASC, `id_post` ASC) VISIBLE,
  INDEX `id_post_dislike_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_dislikes_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dislikes_id_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`Publicacao` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ADICIONAR COLUNAS DE LOCALIZAÇÃO NA TABELA PUBLICACAO
ALTER TABLE `mydb`.`Publicacao` 
ADD COLUMN `local` VARCHAR(255) NULL AFTER `dataPublicao`,
ADD COLUMN `cidade` VARCHAR(100) NULL AFTER `local`,
ADD COLUMN `estado` VARCHAR(50) NULL AFTER `cidade`; 

/* 
	DROP DATABASE mydb; 
/*